### ISSUE TITLE
Isotope Fehler form_checkbox form_radio

### ISSUE THREAD

**Issue by 9teufel** [contao-thememanager/core#1]
Danke für die tolle Erweiterung.

Isotope erzeugt leider folgende Fehler im Checkout:

```
[2021-01-13 08:10:47] request.INFO: Matched route "tl_page.34". {"route":"tl_page.34","route_parameters":{"_token_check":true,"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","pageModel":"[object] (Contao\\PageModel: {})","parameters":"/review","_route":"tl_page.34"},"request_uri":"https://dev.domain.de/shop/checkout/review.html","method":"GET"} []
[2021-01-13 08:10:47] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function prepare() on null" at /www/htdocs/w0101571/dev/2021-01/vendor/contao-thememanager/core/src/Resources/contao/templates/forms/form_radio.html5 line 3 {"exception":"[object] (Error(code: 0): Call to a member function prepare() on null at /www/htdocs/w0101571/dev/2021-01/vendor/contao-thememanager/core/src/Resources/contao/templates/forms/form_radio.html5:3)"} []
[2021-01-13 08:11:25] request.INFO: Matched route "tl_page.34". {"route":"tl_page.34","route_parameters":{"_token_check":true,"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","pageModel":"[object] (Contao\\PageModel: {})","parameters":"/review","_route":"tl_page.34"},"request_uri":"https://devdomain.de/shop/checkout/review.html","method":"GET"} []
[2021-01-13 08:11:25] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function prepare() on string" at /www/htdocs/w0101571/dev/2021-01/vendor/contao-thememanager/core/src/Resources/contao/templates/forms/form_checkbox.html5 line 3 {"exception":"[object] (Error(code: 0): Call to a member function prepare() on string at /www/htdocs/w0101571/dev/2021-01/vendor/contao-thememanager/core/src/Resources/contao/templates/forms/form_checkbox.html5:3)"} []
```

Verwende ich die beiden Contao Core Templates von form_checkbox.html und form_radio.html tritt der Fehler nicht auf.

**Comment by doishub** [comment]
Hallo mecintosch,

dies tritt auf, wenn der StyleManager nicht an das Template übergeben werden konnte. Also wenn Formulare anders als über den Formulargenerator erzeugt wurden und der entsprechende Hook nicht gegriffen hat.

Eine vorübergehende Lösung, ist die StyleManager-Anweisung mit einer IF-Abfrage zu umschließen. Ich denke so werden wir es  im nächsten Update auch im Core übernehmen. Folgendes müsste dann in beiden Templates (`form_checkbox.html5`, `form_radio.html5`) gemacht werden:

*Vorher:*
```html+php
<?= $this->styleManager->prepare('gridList')->format(' %s') ?>
```
*Nachher:*
```html+php
<?= $this->styleManager ? $this->styleManager->prepare('gridList')->format(' %s') : '' ?>
```

**Comment by mecintosch** [comment]
Danke für rasche Hilfe.
Hab den Code in beiden Templates ersetzt, aber leider immer noch der gleiche Fehler.

![Bildschirmfoto 2021-01-13 um 08 48 07](https://user-images.githubusercontent.com/16761621/104421778-1ade1600-557c-11eb-9c96-efb4b6752f02.png)
![Bildschirmfoto 2021-01-13 um 08 48 14](https://user-images.githubusercontent.com/16761621/104421788-1ca7d980-557c-11eb-9f0e-dd61254fdb08.png)

**Comment by doishub** [comment]
Hast du den Cache an und könntest den ggf. mal leeren?

**Comment by mecintosch** [comment]
Cache ist geleert. Fehler kommt auch mit aktiviertem Debug-Modus.

**Comment by doishub** [comment]
Da wir auch einen Isotope-Shop mit diesem "Hack" am laufen haben, vermute ich gerade, dass aus irgendeinem Grund noch immer die alten Templates verwendet werden. Wenn ich das richtig sehe, liegen die Templates aber im root `/templates` Ordner, korrekt?

**Comment by mecintosch** [comment]
Ja genau, die geänderten Templates liegen im `/templates` Hauptordner.

Es wird schon das geänderte Template geladen, im Debug Error steht:

`  <div role="group" aria-label="legend" id="ctrl_<?= $this->id ?>" class="checkbox_container grid-list small-gutter<?php if ($this->class): ?> <?= $this->class ?><?php endif; ?><?= $this->styleManager ? $this->styleManager->prepare('gridList')->format(' %s') : '' ?>">`

Ändere ich die beiden Templates auf Contao Core kommt auch kein Fehler.

**Comment by doishub** [comment]
Je nach PHP-Version könnte ich mir vorstellen, dass wir in der IF-Abfrage ein `isset` o.ä. verwenden sollten.
Versuch bitte mal ob einer der folgenden Varianten hilft:
```php+html
<?= (isset($this->styleManager) ? $this->styleManager->prepare('gridList')->format(' %s') : '') ?>
```
oder
```php+html
<?php if ($this->styleManager): ?> <?= $this->styleManager->prepare('gridList')->format(' %s') ?><?php endif; ?>
```

**Comment by doishub** [comment]
Bei uns liegen Templates übrigens auch in einem Unterordner `/templates/shop`. Sollte m.E. in diesem Fall aber keinen Unterschied machen.

**Comment by mecintosch** [comment]
Habe alle Varianten durchgespielt mit PHP 7.3 und 7.4 aber leider immer noch der Fehler.

Wenn ich den betreffenden Code entferne lädt die Seite. Also das richtige Template wird ganz sicher geladen.

**Comment by doishub** [comment]
Er dürfte mit der Abfrage jedoch nicht mehr die `prepare`-Methode aufrufen. Hast du die Möglichkeit zu debuggen und dir ausgeben zu lassen, was in `$this->styleManager` steht?

**Comment by mecintosch** [comment]
Kann den Fehler schon etwas eingrenzen. Hab die Änderung wie im Post #2 aktiv.

Der Fehler tritt nur auf wenn ich im Isotope Checkout ein Formular (AGB Checkbox) aktiviert habe.

**Comment by doishub** [comment]
Kommt diese Checkbox durch eine Erweiterung? Mir wird diese Einstellung nicht angeboten, oder finde ich diese nicht im Modul selber?

![image](https://user-images.githubusercontent.com/48379929/104437338-ecb60180-558e-11eb-906d-1a9d8b241fae.png)

**Comment by mecintosch** [comment]
Doch ist bei dir auch da, ist das Bestellbedingungsformular.

**Comment by doishub** [comment]
Achso, das kommt dann direkt aus dem Formulargenerator. Und dort im Widget wird auch kein anderes Template verwendet? Sobald ich etwas Zeit finde, versuche ich das auch mal mit einem eigenen Formular über die Option "Bestellbedingungsformular".

**Comment by doishub** [comment]
Könntest du mir bitte deine Einstellungen des Kassenmoduls einmal zur Verfügung stellen? Oder gibt es etwas zu anderes zu beachten, bei der Verwendung eines eigenen Formulars? Ich bekomme das Formular derzeit nicht in meinem Kassenvorgang ausgegeben.

**Comment by mecintosch** [comment]
Eigentlich gibt es nichts zu beachten, das Bestellbedingungsformular kommt im letzten Checkout Step auf der Position wie im Modul angegeben. Im Formulargenerator muss auch nichts weiter eingestellt werden. Es können beliebige Formularfelder eingefügt werden.

**Comment by doishub** [comment]
Es scheint als würde der Hook für die Ausgabe eines Formular-Widgets innerhalb des Kassenvorgangs nicht greifen und der StyleManager dadurch nicht hinzugefügt werden können. Für mich bleibt es jedoch gerade weiterhin ein Rätsel, warum die IF-Abfrage hier nicht entsprechend greift und dennoch die `prepare`-Methode aufrufen möchte. 

Für Formulare innerhalb des Kassenvorgangs müsste vorerst also das normale Widget-Template verwendet werden.

**Comment by mecintosch** [comment]
OK, danke

**Comment by doishub** [comment]
Ggf. wird das Problem bald gelöst werden können:
https://github.com/isotope/core/issues/2202

**Comment by mecintosch** [comment]
Super!

In der neuen Isotope Version (2.7) hat man nun die Möglichkeit eigene Formulare beliebig in jedem Bestellschritt einzufügen. Darum müssen, denke ich, alle Bestellschritte im Checkout berücksichtigt werden. Hoffe das hilf. Danke!

<img width="782" alt="Bildschirmfoto 2021-03-11 um 19 10 03" src="https://user-images.githubusercontent.com/16761621/110834499-e77ae780-829d-11eb-947b-d418f00dabdb.png">
<img width="788" alt="Bildschirmfoto 2021-03-11 um 19 13 34" src="https://user-images.githubusercontent.com/16761621/110834507-e944ab00-829d-11eb-8a1a-0a400dc8e0b4.png">

**Comment by zoglo** [comment]
@9teufel I'm wondering if you still have that issue as it has been fixed a long time ago:
https://github.com/contao-thememanager/core/commit/c6b2f549f68c15f01cd5c32f0aec746baa231615

https://github.com/contao-thememanager/core/blob/b746c2a17ca66e538469aad4b3a1a912e8beed0e/contao/templates/forms/form_checkbox.html5#L3
https://github.com/contao-thememanager/core/blob/b746c2a17ca66e538469aad4b3a1a912e8beed0e/contao/templates/forms/form_radio.html5#L3

I'll close this issue for now. Feel free to reopen it.

**Comment by doishub** [comment]
The problem will unfortunately continue as long as Isotope does not provide field hooks. Other extensions that create forms will also have this problem.

I think the problem can't be solved in general, so I consider the ticket closed for the time being.
