### ISSUE TITLE
Command line interface for building theme 

### ISSUE THREAD

**Issue by NewmansHub** [contao-thememanager/core#11]
I would like to deploy ThemeManager instances directly via a CI/CD. 

At the moment it is unfortunately necessary to log in to contao once and compile the theme, but to deploy websites automatically you need the possibility to generate the theme via the command line. 

Probably this belongs to [contao-theme-compiler-bundle](https://github.com/oveleon/contao-theme-compiler-bundle) but because of the theme ID that is needed for the generation, an integration in the ThemeManager directly is also necessary.

**Comment by zoglo** [comment]
**Will be released in the next version of contao-theme-compiler-bundle**
https://github.com/oveleon/contao-theme-compiler-bundle/compare/master...develop
