### ISSUE TITLE
Boxed text-color-invert wird nicht übernommen

### ISSUE THREAD

**Issue by 9teufel** [contao-thememanager/core#22]
Hallo,

wählt man zB beim Inhaltselement Text Layout => Boxed aus, werde die Klassen "boxed text-color-regular" eingefügt. Mein boxed Hintergrund ist dunkel, deshalb habe ich bei Texts => Text-Color auf "Invert" gestellt. 

Wird aber nicht überschrieben da "text-color-regular" in der CSS Datei nach "text-color-invert" kommt.

Als Workaround habe ich in meiner custom.css

```
.boxed.text-color-invert p,
.boxed.text-color-invert ol,
.boxed.text-color-invert ul,
.boxed.text-color-invert b,
.boxed.text-color-invert strong,
.boxed.text-color-invert .captcha_text,
.boxed.text-color-invert .icon,
.boxed.text-color-invert .hl-design-lined:after {
  color: var(--color-text-invert);
}
```
Vielleicht wäre es möglich "text-color-regular" aus der boxed Element zu entfernen.
Danke!

**Comment by zoglo** [comment]
Hey @9teufel ,

boxed bekommt standardmäßig text-color-regular, da der Background die body-bg ist. So können Boxen auch in einem Artikel mit dunklem Hintergrund angezeigt werden.

Deine geschilderte Lösung könntest du so erstmal nutzen.

Wir arbeiten schon länger an einer 2.0 (Siehe branches), in welcher dies schon berücksichtigt wird.

**Comment by zoglo** [comment]
As this is not an issue but a feature request due to design limitations, I will close this issue for now. It has already been implemented in the development branch (2.0.x-dev).

Your way of implementation does work and is the only way to override it for now.
