### ISSUE TITLE
Feature: Contao core gallery with columns

### ISSUE THREAD

**Issue by 9teufel** [contao-thememanager/core#26]
Es wäre toll wenn in der Standard Contao Galerie auch der Bereich "Grid-List" und eventuell auch Slider zur Verfügung stehen würde.

Derzeit gehe ich bei Galerien den Umweg über das Element "Bild-Liste". Bei vielen Bildern ist die Wartung aber sehr mühsam da hier ja keine kompletten Ordner ausgewählt werden können.

Würde mich freuen – danke!

**Comment by zoglo** [comment]
Hey @9teufel ,

für das normale Galerie-Element war es nicht vorgesehen, dass vom ThemeManager Core das native Template überschrieben wird, da hierbei die Contao-Core-Funktionalitäten
 überschrieben werden:

Folgende Felder würden zum Beispiel nicht funktionieren:
- Vorschaubilder pro Reihe

Paginierungen würden für Slider nicht funktionieren
- Elemente pro Seite
- Anzahl an Elementen

Vererbung in Subtemplates wird nicht funktionieren (Kinds-Template)
- Inhaltselement-Template lässt sich beeinflussen (Klassen und Templatevariablen können hier gesetzt werden)
- Galerie-Template (die Liste) lässt sich leider nicht beeinflussen (Keine Möglichkeit dieses Template mit dem StyleManager zu erreichen)

Nichtsdestotrotz könntest du hierbei die Einstellungen im StyleManager selber hinzufügen und könntest hierbei das "Galerie-Template" in das "Inhaltselement-Template" integrieren.

Zwecks Slider-Einstellungen kannst du dir die 1.x StyleManager-Konfiguration anschauen.

Folgende style-manager-gallery.xml in deinem /templates -Ordner mit aktivierter Bundle-Konfiguration im StyleManager würde die Grid-Liste für die Galerie aktivieren, es würde aber ohne Umbauten des Gallerie-Templates nicht funktionieren:

Inhalt der "style-manager-gallery.xml"
``` 
<?xml version="1.0" encoding="UTF-8"?>
<archives>

  <archive identifier="gridList">
    <field title="identifier">gridList</field>
    <children>
      <child alias="grid-list">
        <field title="alias">grid-list</field>
        <field title="contentElements">a:1:{i:0;s:7:"gallery";}</field>
      </child>
      <child alias="grid-list-xs">
        <field title="alias">grid-list-xs</field>
        <field title="contentElements">a:1:{i:0;s:7:"gallery";}</field>
      </child>
      <child alias="grid-list-s">
        <field title="alias">grid-list-s</field>
        <field title="contentElements">a:1:{i:0;s:7:"gallery";}</field>
      </child>
      <child alias="grid-list-m">
        <field title="alias">grid-list-m</field>
        <field title="contentElements">a:1:{i:0;s:7:"gallery";}</field>
      </child>
      <child alias="grid-list-l">
        <field title="alias">grid-list-l</field>
        <field title="contentElements">a:1:{i:0;s:7:"gallery";}</field>
      </child>
      <child alias="grid-list-xl">
        <field title="alias">grid-list-xl</field>
        <field title="contentElements">a:1:{i:0;s:7:"gallery";}</field>
      </child>
      <child alias="autoHeight">
        <field title="alias">autoHeight</field>
        <field title="contentElements">a:1:{i:0;s:7:"gallery";}</field>
      </child>
      <child alias="justify">
        <field title="alias">justify</field>
        <field title="contentElements">a:1:{i:0;s:7:"gallery";}</field>
      </child>
      <child alias="gutter">
        <field title="alias">gutter</field>
        <field title="contentElements">a:1:{i:0;s:7:"gallery";}</field>
      </child>
    </children>
  </archive>

</archives>

```

**Comment by 9teufel** [comment]
Danke, mit der XML Datei funktioniert es! Das Template habe ich mir schon umgebaut.

**Comment by zoglo** [comment]
Has been introduced in the 2.0.x-dev branch.

Mind that perRow has been dropped as it doesn't have any effect and that the Library-Hint was removed as the grid-list from ctm-framework will deal with it now.
