### ISSUE TITLE
Checkbox labels do not respond to text-color invert

### ISSUE THREAD

**Issue by NewmansHub** [contao-thememanager/core#3]
https://github.com/contao-thememanager/core/blob/66e89c300f2f3f9ca90918c0c773baf7c8034ce0/src/Resources/public/framework/scss/styles/_text-color.scss#L27-L29

**Comment by zoglo** [comment]
Checkbox labels should now react to text-color-invert (and text-color-regular) 9d658587c5eeb0b45ef658be436a32b8cfe33356.
This will be fixed in the next version.

**Comment by zoglo** [comment]
The new release contains new variables that can be used in the thememanager configuration. The invert setting should now work with .text-color-invert:

https://github.com/contao-thememanager/core/releases/tag/1.4.0

- Added $form-checkbox-radio-label-color-invert (Inverted color for labels when using text-color: invert) 9d65858
