### ISSUE TITLE
Bild-Text und Bild-Text-Liste erweitern / Lightbox-Größe

### ISSUE THREAD

**Issue by 9teufel** [contao-thememanager/core#32]
#### Feature-Request

Beim Element "Bild-Liste" gibt es die Option Großansicht/Neues Fenster, damit das Bild in der Lightbox geöffnet werden kann. Es wäre toll wenn die Option auch bei "Bild-Text" und "Bild-Text-Liste" zur Verfügung stehen würde.

#### Bug

Beim Lightbox-Bild sollte die gewählte Bildgröße vom Seitenlayout berücksichtigt werden. Derzeit wird das Originalbild ausgegeben. 

Danke!

**Comment by zoglo** [comment]
@9teufel 
Implemented in #33 - will be added within the next release
