### ISSUE TITLE
Behavior overflow does not have enough power against the boxed shadow list statement

### ISSUE THREAD

**Issue by NewmansHub** [contao-thememanager/core#4]
If a grid-list has the class `boxed-shadow` it is no longer possible to use the class `ov`, because `boxed-shadow` has more weight.
This makes it impossible to set the list overflow: visible.

Is this a bug?

![image](https://user-images.githubusercontent.com/75305857/124559714-4c091600-de3c-11eb-9e8c-cefd4c2f05ee.png)

**Comment by zoglo** [comment]
I moved the .ov class into a separate .scss file. You are right about the fact that it should load after any styles and components.
