### ISSUE TITLE
Translation error in the layout settings

### ISSUE THREAD

**Issue by NewmansHub** [contao-thememanager/core#5]
Under the Theme-Config the descriptions for the variables of the "column-width" are wrong in German version. 

"Hier können Sie den Bruchpunkt für **die das** kleine Spalten-Verhalten einstellen (linke oder rechte Spalte).".

This concerns all 3 variables.

**Comment by zoglo** [comment]
Should be fixed in the next version!

**Comment by zoglo** [comment]
This was fixed in the new release: https://github.com/contao-thememanager/core/releases/tag/1.4.0

- Fixed a translation error for the german column-width descriptions 5661dd1
