### ISSUE TITLE
Normalize input submit style on safari (ios)

### ISSUE THREAD

**Issue by NewmansHub** [contao-thememanager/core#8]
With the Safari browser (iPhone, 14.7.1), buttons with [type=submit] have a default style assigned that is not cleaned up in the Theme Manager.

With -webkit-appearance: none; this can be deactivated. 

https://kulturbanause.de/blog/submit-button-auf-dem-iphone-ipad-ios-stylen/

**Comment by zoglo** [comment]
Hey @NewmansHub,

we already have the option to assign button styles to an input field by assigning them the class "button".

Webkit appearance is already reset on this line:
https://github.com/contao-thememanager/core/blob/53c708313107ce18b814c038a035cc669fb3ed71/src/Resources/public/framework/scss/styles/_button.scss#L22

The question is whether people want input[type=submit] to have the standard appearance or if we want it to act as a button.

**Comment by NewmansHub** [comment]
yep, i agree!
